package javafx.controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;

import java.net.URL;
import java.util.ResourceBundle;
import java.util.SortedSet;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import personnel.Employe;
import personnel.Ligue;
import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class LigueController implements Initializable {
	
	@FXML private Ligue ligue;
	private SortedSet<Employe> employes;
	@FXML private AnchorPane anchorPane;
	@FXML private TableView<Employe> employeTable;
	@FXML private TableColumn<Employe, String> index;
	@FXML private TableColumn<Employe, String> nomEmploye;
	@FXML private Label nomLigue;
	


	@FXML
	public void quitter(ActionEvent event) {
		// TODO Autogenerated
	}

	@FXML
	public void ajouterEmploye(ActionEvent event) {
		// TODO Autogenerated
	}

	@FXML
	public void selectEmploye(ActionEvent event) {
		// TODO Autogenerated
	}

	@FXML
	public void supprimer(ActionEvent event) {
		// TODO Autogenerated
	}

	private void loadEmployes() {
		employes = ligue.getEmployes();
		nomLigue.setText(ligue.getNom());
	}
	public void passData(Ligue ligue) {
		this.ligue = ligue;
	}
	

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		System.out.println(ligue.getNom());
		
	}

	public void sayThis(String string) {
		System.out.println(string);
		
	}

}
