package javafx.controller;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.DatePicker;

public class ModifierPropreCompteController {
	@FXML
	private AnchorPane anchorPane;
	@FXML
	private Label employeAffiche;
	@FXML
	private Label warning;
	@FXML
	private TextField nom;
	@FXML
	private TextField prenom;
	@FXML
	private TextField mail;
	@FXML
	private TextField password;
	@FXML
	private DatePicker dateArrive;
	@FXML
	private DatePicker dateDepart;

	// Event Listener on Button.onAction
	@FXML
	public void sauvegarder(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void quitter(ActionEvent event) {
		// TODO Autogenerated
	}
}
